### ISSUE TITLE
Taskdrome would drag but not drop cards.

### ISSUE THREAD

**Issue by JaapJ** [mantisbt-plugins/Taskodrome#41]
Hello, 

I'm  using: MantisBT 1.2.19, with Plug-in: Taskodrome 0.1
(in a local-host environment, Windows 10 with Wamp-server)

Installed the Taskodrome and could drag but NOT Drop.
so I could not re-assign any issue to someone else by drag-and-drop.

Whom could help me with this issue? 
I assume that I'm facing an configuration issue, but which one?

Thanks in advance,
Cheers, 
Jaap

**Comment by AuthenticEshkinKot** [comment]
Hello @JaapJ ,
I'll try to help you.
Could you open your browser console before trying to drop? Some useful messages may be there.
When you drop an issue does it return to its original position? Does your user have sufficient rights to reassign issues?

**Comment by JaapJ** [comment]
Hello @AuthenticEshkinKot 

Indeed when I drag any card and try to drop it somewhere else then it jumps back to the original position. Opening debug (F12) in the following browsers, IE v11 Chrome v53 or Firefox v48, shows no errors in the console. I'm logged in being Mantis Administrator!

Uninstalled all other plugins but issue is still there!

**Comment by AuthenticEshkinKot** [comment]
@JaapJ 
There is no need to uninstall other plugins - they have no impact on Taskodrome and vice versa.
Could you check your "Workflow Transitions"? All checkboxes should be enabled there. You can find it in "Manage->Manage Configuration->Workflow Transitions"

**Comment by JaapJ** [comment]
@AuthenticEshkinKot
All checkboxes in the section still are enabled in "Manage->Manage Configuration->Workflow Transitions".

**Comment by AuthenticEshkinKot** [comment]
@JaapJ 
I've made a fix that may solve this problem. Get the latest version from mantisbt_1.2.9 branch, please.

**Comment by JaapJ** [comment]
@AuthenticEshkinKot
Downloaded new Taskodrome for  MBT 1.2.9 >=
Still could not drag and drop.
Even not after restarting the Wamp-server…

But I get the following error when I double click in Windows the recent modified file known:
mantisbt-1.2.19\plugins\Taskodrome\scripts\on_load_opening.js
Then I get an error known:

Script:
c:\wamp64\www\mantisbt-1.2.19\plugins\Taskodrome\scripts\on_load_opening.js
Line: 48
Char: 1
Error : ‘document’ is undefined
Code: 800A1391
Source: Microsoft Jscript runtime error

The other .js files in that directory do show any error like above.

To be sure testing the plug-in correctly I reproduced this issue twice (by re-installing plug-in)
Thanks in advance for all your care...

**Comment by AuthenticEshkinKot** [comment]
@JaapJ 
https://yadi.sk/d/SowrVtdhvAsXE - this is devs_grid.js with new log messages. Replace your mantisbt/plugins/Taskodrome/scripts/devs_grid.js with it, please. Then open browser console, drag'n'drop an issue and copypaste log messages here.

**Comment by JaapJ** [comment]
@AuthenticEshkinKot

Tested at MantisBT 1.2.20 , Windows 10

Within Firefox v48 
(The card will not drop it stucks to the mouse pointer with the new installed dev_grids.js  (patch). I'm not sure or this is expected or not) 
We get the following message in the browser its debug console:

TypeError: allowed_statuses_map[selectedCard.value.id][selectedCard.value.status] is undefined
onPressUp()
devs_grid.js:67
b.on/<()
easeljs-0.8.2.min.js:12
b._dispatchEvent()
easeljs-0.8.2.min.js:12
b.dispatchEvent()
easeljs-0.8.2.min.js:12
b._dispatchMouseEvent()
easeljs-0.8.2.min.js:13
b._handlePointerUp()
easeljs-0.8.2.min.js:13
b._handleMouseUp()
easeljs-0.8.2.min.js:13
b.enableDOMEvents/d.mouseup.f()
easeljs-0.8.2.min.js:13

Which browser you prefer for trouble shooting?
MantisBT runs everywhere  in different browsers. 

Remarks:
1) Internet Explorer v.11 The drag and drop keeps jumping back to original position without any message in the debug-console.

2) In Chrome v.53 it throws same kind of error like Firefox

3) In Edge we get the error:
SCRIPT5007: Unable to get property 'length' of undefined or null reference
plugin.php (65,7)
See:
https://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=NL-NL&k=k(VS.WebClient.Help.SCRIPT5007)

4)When I try to open easeljs.0.8.2min.js  (windows double click) then it reports an error in line 12, column 4765 Code 800A1391 Console not defined.

**Comment by AuthenticEshkinKot** [comment]
@JaapJ 
Thanks for detailed answer! Now I see the reason of such strange behavior.
Honestly, there are only two types of browsers for me - IE and not-IE, because in IE JS runs in one way, while in not-IE in another way. So, IE and Chrome/FF would be enough for troubleshooting.

**Comment by AuthenticEshkinKot** [comment]
@JaapJ 
I've pushed a new commit - try it, please. Maybe it will help, otherwise I suggest you to check is it possible to change issue's assignee/status using default mantisbt interface with same user and for same project.

**Comment by xxyy** [comment]
I also had this issue on MantisBT 1.3.0-rc2. Mentioned changes did not fix it for me - the assignment board was working, but not the status board. After some fun with Chrome's JS debugger, I found the issue outlined in #49. With these changes, the status board works again for me. :)

**Comment by AuthenticEshkinKot** [comment]
@xxyy 
Thanks for help! I've accepted your request.
@JaapJ 
There is one more commit that maybe will help you =) Check it, please.

**Comment by JaapJ** [comment]
@AuthenticEshkinKot

The yesterdays fix did fail but the one of today was success full.
I tested this for  IE v11, Chrome, Firefox, Opera and Edge (most recent versions)
it works like charm. Thanks for fixing this wonderful feature.

Closing this issue!
