### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by hendy1** [mantisbt-plugins/Taskodrome#95]
i have install taksodrome on mantisbt 2.1.0

the installation process is like this

1. i download the code
2. upload to mantisbt/plugin

then when i open the taskodrome tab, it doesn't display anything except for the [ Assignment board ] [ Status board ] 
![mantisbt-issues](https://cloud.githubusercontent.com/assets/25633810/22730534/f7282020-ee19-11e6-8bc4-fce54328d1f8.png)
![mantisbt-taskodrome](https://cloud.githubusercontent.com/assets/25633810/22730535/f72854dc-ee19-11e6-8520-59162f0414cf.png)

**Comment by AuthenticEshkinKot** [comment]
Hello, @hendy1 
Could you show your console output?

**Comment by hendy1** [comment]
sorry i'm new at this, so i'm not really using any console though

but when i'm using the inspect element option at the console tab nothing appears
![asd](https://cloud.githubusercontent.com/assets/25633810/22734439/45522184-ee28-11e6-92a1-fc12e5c10df6.png)

**Comment by rmeske** [comment]
@hendy1,
While the Console is open, try navigating away and then back to Taxodrome.  This will then capture anything written to the console log.

**Comment by hendy1** [comment]
here is the console output
![asd](https://cloud.githubusercontent.com/assets/25633810/22765507/443c6770-eea3-11e6-9b4b-22ad67eba466.png)

**Comment by AuthenticEshkinKot** [comment]
@hendy1 
I've added some new log messages, that may help me to solve your problem. Please, update your Taskodrome and refresh its page with console opened. After that, post its output here, just like you did it earlier.

**Comment by hudrywudry** [comment]
@ AuthenticEshkinKot, 
i have exatly the same issue like hendy1,.

mantisbt 2.1.0
php 7.0.13
5.5.5-10.1.19-MariaDB 

i also have a htaccess password on the login page, maybe thats the problem

here you can see my console errors

![taskodrome_issue_01](https://cloud.githubusercontent.com/assets/26009486/23311776/965de8ba-fab7-11e6-958f-094746bf1843.jpg)

**Comment by AuthenticEshkinKot** [comment]
@hudrywudry 
Looks like you haven't got enough rights to access Taskodrome's scripts. Do you have such a file https://github.com/mantisbt-plugins/Taskodrome/blob/mantisbt_2.0.0/Taskodrome/.htaccess?

**Comment by hudrywudry** [comment]
hi AuthenticEshkinKot,
yes, there is such an .htaccess file with exactly this content.
is this correct or should i change somthing?

thx

**Comment by AuthenticEshkinKot** [comment]
@hudrywudry 
It's OK, it should be there. Anyway, it looks like you have problem with Apache settings, because it doesn't allow you to load plugin's scripts.

**Comment by EthraZa** [comment]
I got the same problem. Any hints?

**Comment by EthraZa** [comment]
Oh, found it.

Just changed **Taskodrome/.htaccess** to
`Require all granted`

**Comment by AuthenticEshkinKot** [comment]
@EthraZa 
Thanks for help!
Did you replace all lines in **Taskodrome/.htaccess** or just add the new one?

**Comment by EthraZa** [comment]
@AuthenticEshkinKot 
I've just replaced all and it worked. Didn't try to add, don't  know if it would work too.

**Comment by AuthenticEshkinKot** [comment]
@hendy1 @hudrywudry @EthraZa 
I've added a commit for this issue, please, check it out.

**Comment by froilanserohijos** [comment]
I have the same issue. OI can only see Users with Admin Rights in my Taskodrome Assignment Board.

May I ask help what did I miss-out?

![image](https://user-images.githubusercontent.com/16287774/27819064-1064fa58-60cb-11e7-9f1b-e5c6b1b19088.png)

**Comment by gamerboy11** [comment]
I am new to mantis BT, but I have it all working really well now (Windows server platform)
Your plugin is the first I installed and activated. But not much is showing up when I click on the Taskodrone button in the toolbar. Not sure what is going on, since everything else is working in the program so far

Here is what I see in the web page (using latest chrome browser)
![image](https://user-images.githubusercontent.com/41450503/42967404-bac1ccea-8b65-11e8-9c2f-88e5eef2029b.png)

I looked in the console and I see these messages
![image](https://user-images.githubusercontent.com/41450503/42967494-06f15144-8b66-11e8-9a22-a7d0eb221256.png)


Any ideas what is going on here?  THere are a few other plugins that got installed by default when I installed Mantis, and those are working like gravatar

**Comment by AuthenticEshkinKot** [comment]
@gamerboy11 
There are some problems with newer (>=2.8.0) versions of mantisbt.

**Comment by gamerboy11** [comment]
hmmm I didnt know there was a version of mantisBT greater than 2.15.0 that is available to download. What is version 2.8.0 that you mentioned?

**Comment by atrol** [comment]
>  I didnt know there was a version of mantisBT greater than 2.15.0 that is available to download

There is none. 2.15.0 is the latest one at the moment, 2.16.0 will follow the next days.
2.8.0 is older than 2.15.0, I assume you got a bit confused by the numbers.

**Comment by AuthenticEshkinKot** [comment]
@gamerboy11 
I've fixed this problem, please check it out.

**Comment by gamerboy11** [comment]
Sorry about that, yeah, for some reason I just thought it was like 2.8 vs 2.1.5 not 2.15, even though its obviously different than that. So do I just download your latest code and try it again?

Thanks!

**Comment by gamerboy11** [comment]
So I downloaded the latest from git hub, and copied the taskodrome folder into the plugins directory on my Windows server where this is running. Same thing happens.

**Comment by AuthenticEshkinKot** [comment]
What browser do you use?
Try Shift-F5 or Ctrl-R.

**Comment by AuthenticEshkinKot** [comment]
I've fixed one more bug, try it again

**Comment by gamerboy11** [comment]
I have tried in IE10 IE11 and chrome, I can also try in firefox. Not sure if I tried that.
OK, will try again now. Thanks!

**Comment by gamerboy11** [comment]
Its not showing the drag and drop taskodrome screen yet. I still see the same screen as I first mentioned in this thread. 

I did click on the configuration screen, and I do see that. So that is working. Just wanted to let you know that.

![taskodrome1](https://user-images.githubusercontent.com/41450503/43040590-988c33fa-8d0d-11e8-9952-40c3168ad5bd.png)

**Comment by gamerboy11** [comment]
Also, here is the latest F12 errors I see. I have never seen this type of an error before. It shows up in all the browsers too. And it seems to be related to loading the css file. I would imagine if it cant load the taskodrome.css file....that it will never look or work correctly. I wish I knew why it was complaining about that issue. I googled it several times, and didnt really get any answers yet. So I thought I would mention it again.  

I was wondering if there is a different way to trick it to load this css file using some other syntax, in my case, just to see if it will work then. Can I hard code something on my copy of your files, to force it to load that css file?  Then maybe at least it will work for the time being until we know whats c
![taskodromef12errors](https://user-images.githubusercontent.com/41450503/43040625-706906cc-8d0e-11e8-9614-eb1e2f4fbcb0.png)
ausing it.

**Comment by AuthenticEshkinKot** [comment]
I've tested the plugin in Chrome, Firefox (on linux) and IE 11 and got no errors.
There is no MIME type "text/html" in main.php. Are you sure, that you fully updated Taskodrome in mantisbt plugins directory? Are you sure, that you downloaded the plugin from the master branch?

**Comment by gamerboy11** [comment]
yep, I did exactly those things. 

Maybe there is something wrong with my Microsoft IIS web server that is causing this? As an example I had to configure a mime type for those .woff2 files, otherwise the text shown on all the web pages of Mantis BT was not looking good. Once I did that, it worked great.  And I could use the admin options in MantisBT to select the different default fonts. And it worked good. But before I added that woff2 mime type is appeared to be broken. So now I am wondering if this has to do with my web server.

Obviously your code works for 99% of the cases ;-)  but something in my environment seems to be blocking it from working.   Everything else in manstis bt is working though. So that error message in yellow text above in the screenshot sure seems like it must be causing some problems.

**Comment by gamerboy11** [comment]
I wish I knew why or how to fix it, would love to use your plugin!!!! I am about to show off mantis BT to the rest of the development team. We are going to stop using our old bug tracker and start using this Mantis BT tracker. But would love to have this plugin working too.

**Comment by gamerboy11** [comment]
Also, I was trying another plugin, and I get a very similar error. This makes me think even more that something is a little off with my IIS web server :-(

Here is the other error from a different plugin....seems like same exact thing is happening with Mantis BT for my plugins.

UGH!
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://192.168.1.111/bt/plugin_file.php?file=Announce/announce.css".
plugin_file.php?file=Announce/announce.js:1

**Comment by gamerboy11** [comment]
here is another screenshot of one of the errors the browser is reporting about the UnCaught Syntax error. Not sure whats up with that.  Just thought I would put a screenshot of that in here too, so you can see the other error that I am getting. if you look back at my first or second screenshot, you see I am getting one of these errors for every js file (I think) that is related to the taskodrome plugin.

![taskodrome js file error](https://user-images.githubusercontent.com/41450503/43050926-5dbe8fce-8dd6-11e8-938b-bcf1588f3c53.png)

**Comment by AuthenticEshkinKot** [comment]
What version of PHP do you use?
I use 5.5.14 and I found same errors as yours.

**Comment by AuthenticEshkinKot** [comment]
Surprisingly, there are no such troubles in MantisBT 2.6.0.

**Comment by gamerboy11** [comment]
I am using php 7.2.2

**Comment by AuthenticEshkinKot** [comment]
Could you try the plugin in MantisBT 2.6.0?

**Comment by gamerboy11** [comment]
I cant change the version of Mantis BT on this server, because we are using it now. Sorry about that.

When I have a little free time, I could try to load version 2.6.0 on another Windows 2008 R2 server that I would have to setup on a virtual server along with IIS, and see if it works or not. But it sounds like you already know it works OK in that version ;-)

**Comment by AuthenticEshkinKot** [comment]
@gamerboy11 
Could you refresh Taskodrome page and then check your PHP log?

**Comment by AuthenticEshkinKot** [comment]
Probably, there will be string "PHP Fatal error:  Class 'finfo' not found", which can be fixed by installation of php-fileinfo.

**Comment by gamerboy11** [comment]
its working!!! thanks so much for helping with this. So it seems like not having that fileinfo extension must have been causing it to fail for some reason.  I can see all 3 of the taskodrome main pages now. NICE!

**Comment by gamerboy11** [comment]
Now I thought I would assign a relationship from one issue, to another issue. And it shows up that way when I click into the issue detail view. But when I click on the relationship taskodrome button, it doesnt show any relationships, even though I assigned a relationship between two issues.  Is there any reason you can think of as to why the relationship would show up in the issue detail screen, but no relationship is shown in the taskodrome screen?

Thought it would be useful to see those relationships. Wonder if I need something else installed on the server, to make that work?

Thanks

**Comment by AuthenticEshkinKot** [comment]
@gamerboy11 
Unfortunately, relationship of kind "related to" is not supported on this board, only "parent of" and "child of" are supported.

**Comment by iherrmann** [comment]
Is Mantis BT supposed to save changes in assignments and status, when i drag&drop an issue in TaskoDrome? At the moment i can move issues from version 4.44 to 4.45 and from engineer 1 to tester 2 and from resolved to feedback, alas al these changes are void after i switch to "view issues" and back to taskodrome. I am not sure, is taskodrome a viewer or a tool with ability to change things?

**Comment by AuthenticEshkinKot** [comment]
@iherrmann 
It should be able to change things

**Comment by MimirRnD** [comment]
We are experiencing the same in Mantis BT 2.20.
Taskodrome is not visible.
I have finfo installed and have added the .htaccess, but nothing is visible in Taskodrome anyway
